name: Deploy to EC2

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '^18'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: npm run build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --no-times --no-perms --delete --exclude '.env'
          path: ./out/
          remote_path: /var/www/html/
          remote_host: ldap.deliver.ar
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

