name: Deploy to ECR and Terraform

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '^18'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: npm run build
      - name: Set up AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_session_token = ${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials

          echo "[default]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config
      - name: Copy files to S3
        run: |
          aws s3 sync ./out s3://eventify-inhouse-frontend
